import type { ViewerLabels } from "./types.js";

export const defaultLabels: ViewerLabels = {
  close: "Close",
  next: "Next image",
  previous: "Previous image",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  resetZoom: "Reset zoom",
  rotate: "Rotate",
  enterFullscreen: "Fullscreen",
  exitFullscreen: "Exit fullscreen",
  share: "Share",
  download: "Download",
  play: "Start slideshow",
  pause: "Pause slideshow",
  showThumbnails: "Show thumbnails",
  hideThumbnails: "Hide thumbnails",
  feedbackQuestion: "Is this photo helpful?",
  feedbackYes: "Yes",
  feedbackNo: "No",
  feedbackSkip: "skip",
  feedbackThanks: "Thanks for the feedback",
  loadFailed: "This image could not be loaded",
  retry: "Try again",
  copiedLink: "Link copied",
  caption: "{group} image {index} of {total} : {title}",
  counter: "{index} / {total}",
  allGroups: "All",
};
